Create SEQUENCE COLETA_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE TBL_COLETA (
    ID INTEGER DEFAULT COLETA_SEQ.NEXTVAL NOT NULL,
    ENDERECO VARCHAR2(200) NOT NULL,
    QTD_RESIDUOS INTEGER NOT NULL,
);